### ISSUE TITLE
floatToRgbe seems doesn't work

### ISSUE THREAD

**Issue by bbbbx** [enkimute/hdrpng.js#5]
[floatToRgbe](https://github.com/enkimute/hdrpng.js/blob/master/hdrpng.js#L240) seems doesn't work for some float point number.

for example:
```js
const rgbe = floatToRgbe(new Float32Array([0.5, 0.5, 0.5])); // [0, 0, 0, 127]
// result should be [128, 128, 128, 128]

// convert back: failed
const float = rgbeToFloat(rgbe); // [0, 0, 0]

// use correct rgbe
rgbeToFloat(new Uint8Array([128, 128, 128, 128])); // [0.5, 0.5, 0.5]
```

**Comment by GitHubDragonFly** [comment]
Just for anybody who might be looking this up in the future.

I did make some additional changes to the `floatToRgbe` function in the hdrpng version I am using in my repository.

This appears to be working properly and the mentioned changes could be seen [here](https://github.com/GitHubDragonFly/GitHubDragonFly.github.io/blob/main/viewers/static/js/hdrpng/hdrpng.js#L240).

My [IMG2MESH](https://githubdragonfly.github.io/viewers/templates/IMG2MESH.html) viewer / converter is using this as an HDR export option (whether with or without Y-flip).
